## SQLite version 3.x
##   gem install sqlite3
##
##   Ensure the SQLite 3 gem is defined in your Gemfile
##   gem 'sqlite3'
##
#
##default: &default
##  adapter: postgresql
##  timeout: 5000
##  database: moss
##  encoding: utf8
##  host: moss1.c9gazzpy3zya.us-west-2.rds.amazonaws.com
##  port: 5432
##  username: knn1989
##  password: rrg-Lsu-VNY-KA4
##  min_messages: warning
##  pool: 5
##  timeout: 5000
#
#development:
##  <<: *default
#  adapter: postgresql
#  timeout: 5000
#  database: moss
#  encoding: utf8
#  host: mossdevelopment.c9gazzpy3zya.us-west-2.rds.amazonaws.com
#  port: 5432
#  username: knn1989
#  password: rrg-Lsu-VNY-KA4
#  min_messages: warning
#  pool: 5
#  timeout: 5000


#development:
##  <<: *default
#  adapter: mysql2
#  timeout: 5000
#  database: mossmysql
#  encoding: utf8
#  host: localhost
#  port: 3306
#  username: root
#  password: 0934084534
#  min_messages: warning
#  pool: 5
#  timeout: 5000

## Warning: The database defined as "test" will be erased and
## re-generated from your development database when you run "rake".
## Do not set this db to the same as development or production.
#test: &test
#  adapter: postgresql
#  timeout: 5000
#  database: moss
#  encoding: utf8
#  host: aa122fghwng5b24.c9gazzpy3zya.us-west-2.rds.amazonaws.com
#  port: 5432
#  username: knn1989
#  password: rrg-Lsu-VNY-KA4
#  min_messages: warning
#  pool: 5
#  timeout: 5000
#
#production:
#  # <<: *default
#  # database: db/production.sqlite3
#  adapter: postgresql
#  adapter: postgresql
#  timeout: 5000
#  database: moss
#  encoding: utf8
#  host: mydbinstance.c9gazzpy3zya.us-west-2.rds.amazonaws.com:5432
#  port: 5432
#  username: knn1989
#  password: 0934084534
#  min_messages: warning
#  pool: 5
#  timeout: 5000
#
#cucumber:
#  adapter: postgresql
#  timeout: 5000
#  database: moss
#  encoding: utf8
#  host: moss1.c9gazzpy3zya.us-west-2.rds.amazonaws.com
#  port: 5432
#  username: knn1989
#  password: rrg-Lsu-VNY-KA4
#  min_messages: warning
#  pool: 5
#  timeout: 5000

test:
  adapter: mysql2
  timeout: 5000
  database: mossmysql_test
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  username: root
  password: 0934084534
  password: rootpw
  min_messages: warning
  pool: 5
  timeout: 5000

development:
 # adapter: mysql2
 # timeout: 5000
 # database: mossmysql
 # encoding: utf8
 # host: 127.0.0.1
 # port: 3306
 # username: root
 # password: 0934084534
 # min_messages: warning
 # pool: 5
 # timeout: 5000

  adapter: mysql2
  timeout: 5000
  database: heroku_16334637a8aeebb
  encoding: utf8
  host: us-cdbr-iron-east-03.cleardb.net
  port: 3306
  username: b5f290e52fa8cf
  password: 5c62811c
  min_messages: warning
  pool: 5
  timeout: 5000
 # adapter: mysql2
 # timeout: 5000
 # database: heroku_16334637a8aeebb
 # encoding: utf8
 # host: us-cdbr-iron-east-03.cleardb.net
 # port: 3306
 # username: b5f290e52fa8cf
 # password: 5c62811c
 # min_messages: warning
 # pool: 5
 # timeout: 5000
production:
  # <<: *default
  # database: db/production.sqlite3
  adapter: mysql2
  timeout: 5000
  database: heroku_16334637a8aeebb
  encoding: utf8
  host: us-cdbr-iron-east-03.cleardb.net
  port: 3306
  username: b5f290e52fa8cf
  password: 5c62811c
  min_messages: warning
  pool: 5
  timeout: 5000
